[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Gobot"
authors = [{name = "Mateo A", email = "gobrowse.alt@proton.me"}]
dynamic = ["version", "description"]
